# Generated by Django 3.0.5 on 2020-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nrp', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=60)),
                ('alamat', models.CharField(max_length=255)),
            ],
        ),
    ]
